<?php

namespace AppBundle\Repository;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends \Doctrine\ORM\EntityRepository
{
    public function getNotParentCategories()
    {
        $categories = $this->createQueryBuilder('category')
            ->where('category.id', 'NOT IN', $this->createQueryBuilder('category')->select('category.parent_id'))
            ->getQuery()->getArrayResult();

        return $categories;
    }
}
