AppBundle\Entity\Category:
    type: entity
    table: category
    repositoryClass: AppBundle\Repository\CategoryRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: '50'
            unique: true
    lifecycleCallbacks: {  }
    oneToMany:
        attributes:
            targetEntity: Attribute
            mappedBy: category
        children:
            targetEntity: Category
            mappedBy: parent
        items:
            targetEntity: Item
            mappedBy: category
    manyToOne:
        parent:
            targetEntity: Category
            inversedBy: children
