AppBundle\Entity\Image:
    type: entity
    table: image
    repositoryClass: AppBundle\Repository\ImageRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        file:
            type: string
            length: '50'
            nullable: true
            unique: true
    lifecycleCallbacks: {  }
    manyToOne:
        item:
            targetEntity: Item
            inversedBy: images


