AppBundle\Entity\User:
    type: entity
    table: user
    repositoryClass: AppBundle\Repository\UserRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        username:
            type: string
            length: '50'
            unique: true
        email:
            type: string
            length: '50'
            unique: true
        password:
            type: string
            length: '100'
            unique: true
    lifecycleCallbacks: {  }
    oneToMany:
        items:
            targetEntity: Item
            mappedBy: user
